web:
  restart: always
  build: ./web
  expose:
    - "8000"
  volumes:
    - /usr/src/web/static
  env_file: .env
  command: /usr/local/bin/gunicorn -w 2 -b :8000 app:app
  privileged: true

nginx:
  restart: always
  build: ./nginx
  ports:
    - "80:80"
  volumes_from:
    - web
  links:
    - web:web
